# To override values here make a file named 'Gruntconfig--custom.yml' - it will be git ignored

plDir: pattern-lab/
jsDir: js/
scssDir: scss/
scssDest: css/style.css
scssConfigRoot: ./
serverDir: ./
serverPath: pattern-lab/public/
openBrowserAtStart: true
updateAtStart: true
buildModernizrAtStart: true
regressionTestRoot: pattern-lab/source/_patterns/
