css:
  enabled: true
  src:
    - scss/**/*.scss
    - source/_patterns/**/*.scss
  dest: dest/
  flattenDestOutput: true
  lint:
    enabled: false
    failOnError: true
  sourceComments: false
  sourceMapEmbed: false
  # tell the compiler whether you want 'expanded' or 'compressed' output code
  outputStyle: expanded
  autoPrefixerBrowsers: # https://github.com/ai/browserslist#queries
    - last 2 versions
    - IE >= 9
  includePaths:
    - ./node_modules
  sassdoc: # http://sassdoc.com
    enabled: true
    dest: dest/sassdoc
    verbose: false
    basePath: https://github.com/phase2/pattern-lab-starter/blob/master/scss
#    exclude:
#      - file.scss
    theme: default
    sort: # http://sassdoc.com/customising-the-view/#sort
      - file
      - group
      - line>
js:
  enabled: true
  src:
    - js/**/*.js
  dest: dest/
  destName: script.js
  sourceMapEmbed: false
  uglify: false
  babel: true
  eslint:
    enabled: true
    src:
      - js/**/*.js
      - gulpfile.js
patternLab:
  enabled: true
  configFile: pattern-lab/config/config.yml
  watchedExtensions:
    - twig
    - json
    - yaml
    - yml
    - md
    - jpg
    - jpeg
    - png
#  injectFiles:
#    - source/styleguide/styleguide.js
#    - source/styleguide/custom-styleguide-specific.css
 #   - ../../modules/**/*.css
  injectBower: true
  scssToJson:
    -
      src: source/_patterns/00-base/01-colors/_color-vars.scss
      dest: source/_patterns/00-base/01-colors/colors.json
      lineStartsWith: $c-
      allowVarValues: false
    -
      src: source/_patterns/01-atoms/01-typography/fonts/_fonts.scss
      dest: source/_patterns/01-atoms/01-typography/fonts/font-sizes.json
      lineStartsWith: $fs--
      allowVarValues: false
    -
      src: source/_patterns/01-atoms/01-typography/fonts/_fonts.scss
      dest: source/_patterns/01-atoms/01-typography/fonts/font-families.json
      lineStartsWith: $ff--
      allowVarValues: false
    -
      src: source/_patterns/00-base/breakpoints/_breakpoints.scss
      dest: source/_patterns/00-base/breakpoints/breakpoints.json
      lineStartsWith: $bp--
      allowVarValues: false
    -
      src: source/_patterns/00-base/spacing/_spacing.scss
      dest: source/_patterns/00-base/spacing/spacing.json
      lineStartsWith: $spacing--
      allowVarValues: false
icons:
  enabled: true
  src: images/icons/src/*.svg
  dest: dest/
  fontPathPrefix: ''
  classNamePrefix: icon
  autohint: false
  normalize: true
  templates:
    enabled: true
    css:
      src: images/icons/templates/_icons.scss
      dest: scss/00-config/
    demo:
      src: images/icons/templates/icons.twig
      dest: source/_patterns/01-atoms/images/
  formats:
    - ttf
    - eot
    - woff
    - svg
browserSync:
  enabled: true
  port: 3050
  watchFiles:
    # - template.php
  # domain: mysite.dev # enable when full CMS is set up
  baseDir: ./
  startPath: pattern-lab/public/
  openBrowserAtStart: false
  # requires above to be true; allows non-default browser to open
  browser:
    - Google Chrome
  # Tunnel the Browsersync server through a random Public URL
  # -> http://randomstring23232.localtunnel.me
  tunnel: false
  reloadDelay: 50
  reloadDebounce: 750
drupal:
  enabled: true
  watch:
    - templates/**
  command: drush cc all
  # in this directory
  dir: ./
  inject:
    bower: true
    file: patternlab.info.yml
